export const sellers = [
  { vendedor: "María Fernanda López García", contado: 700, credito: 0, total: 700 },
  { vendedor: "Pedro Antonio Gómez Torres", contado: 250, credito: 250, total: 500 },
  { vendedor: "Juan Carlos Pérez Rodríguez", contado: 100, credito: 200, total: 300 },
  { vendedor: "Luis Alberto Hernández Morales", contado: 400, credito: 100, total: 500 },
  { vendedor: "Ana María Martínez Ramírez", contado: 600, credito: 300, total: 900 },
  { vendedor: "Carlos Eduardo Fernández Muñoz", contado: 500, credito: 400, total: 900 },
  { vendedor: "Elena Isabel García López", contado: 200, credito: 300, total: 500 },
  { vendedor: "Sofía Margarita Sánchez Díaz", contado: 800, credito: 100, total: 900 },
  { vendedor: "Jorge Luis Rodríguez Cruz", contado: 350, credito: 150, total: 500 },
  { vendedor: "Marta Alejandra Ruiz Herrera", contado: 100, credito: 200, total: 300 },
  { vendedor: "Rafael Ignacio Castro Gómez", contado: 450, credito: 50, total: 500 },
  { vendedor: "Claudia Patricia Morales Jiménez", contado: 300, credito: 200, total: 500 },
  { vendedor: "Gustavo Andrés Ortiz Castillo", contado: 700, credito: 100, total: 800 },
  { vendedor: "Paula Andrea Díaz Flores", contado: 250, credito: 250, total: 500 },
  { vendedor: "Daniel Alejandro Romero Vega", contado: 900, credito: 0, total: 900 },
]